title: Arijit Dutta
# author: Arijit Dutta
# email: arijit.dutta@iitb.ac.in
# repo: "https://github.com/arijitdutta67/homepage"

# urls
# your gh-pages url: https://username.github.io
# url: https://arijitdutta67.github.io
# your repository name: /repository
baseurl: /homepage
minima:
  date_format: "%b %-d, %Y"
  
# analytics if desired (and use environment variable on build command)
google_analytics: UA-74844011-1

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
#theme: jekyll-theme-midnight
#remote_theme: jekyll/jekyll-theme-midnight
